# Generated by Django 5.0.2 on 2024-03-19 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ormapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('bookid', models.IntegerField(primary_key=True, serialize=False)),
                ('bookname', models.CharField(max_length=20)),
                ('author', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('publishdate', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='StudentData',
        ),
    ]
